"""modify table link

Revision ID: ad8948d8dbd7
Revises: b42de372d7ee
Create Date: 2019-04-19 16:33:15.597867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad8948d8dbd7'
down_revision = 'b42de372d7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('name22', sa.String(length=30), nullable=True))
    op.drop_column('link', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('link', 'name22')
    # ### end Alembic commands ###
