"""add xxx 

Revision ID: e16bab08afda
Revises: 92f8d04ebccf
Create Date: 2019-04-19 15:57:32.162812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16bab08afda'
down_revision = '92f8d04ebccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('replied_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'replied_id')
    # ### end Alembic commands ###
